config/routes.rb
Rails.application.routes.draw do
  resources :requirements do
    resources :proposals
  end

  resources :domain_models do
    member do
      post :replace
    end
  end

  root 'requirements#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domain_model.rb
class DomainModel < ApplicationRecord

  def requirements_ref
    [
      Requirement.where('condition like ?', "%#{placeholder}%"),
      Requirement.where('description like ?', "%#{placeholder}%"),
      Requirement.where('remark like ?', "%#{placeholder}%")
    ].inject(:or)
  end

  def requirements
    [
      Requirement.where('condition like ?', "%#{name}%"),
      Requirement.where('description like ?', "%#{name}%"),
      Requirement.where('remark like ?', "%#{name}%")
    ].inject(:or)
  end

  def placeholder
    "$domain:#{id}$"
  end

  def replace!
    transaction do
      requirements.each do |r|
        r.update!(condition: r.condition.gsub(name, placeholder))
        r.update!(description: r.description.gsub(name, placeholder))
        r.update!(remark: r.remark.gsub(name, placeholder))
      end
    end
  end
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  belongs_to :requirement
end

app/models/requirement.rb
class Requirement < ApplicationRecord
  extend Enumerize

  has_many :proposals

  enumerize :status, in: %i[in-review fixed]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/domain_models_controller.rb
class DomainModelsController < ApplicationController
  before_action :set_domain_model, only: [:show, :edit, :update, :destroy, :replace]

  # GET /domain_models
  def index
    @domain_models = DomainModel.all
  end

  # GET /domain_models/1
  def show
  end

  # GET /domain_models/new
  def new
    @domain_model = DomainModel.new
  end

  # GET /domain_models/1/edit
  def edit
  end

  # POST /domain_models
  def create
    @domain_model = DomainModel.new(domain_model_params)

    if @domain_model.save
      redirect_to @domain_model, notice: 'Domain model was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /domain_models/1
  def update
    if @domain_model.update(domain_model_params)
      redirect_to @domain_model, notice: 'Domain model was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /domain_models/1
  def destroy
    @domain_model.destroy
    redirect_to domain_models_url, notice: 'Domain model was successfully destroyed.'
  end

  def replace
    @domain_model.replace!
    redirect_to @domain_model
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_domain_model
      @domain_model = DomainModel.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def domain_model_params
      params.require(:domain_model).permit(:name, :desc)
    end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :set_requirement
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]

  # GET /proposals
  def index
    @proposals = @requirement.proposals
  end

  # GET /proposals/1
  def show
  end

  # GET /proposals/new
  def new
    @proposal = @requirement.proposals.build
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  def create
    @proposal = @requirement.proposals.build(proposal_params)

    if @proposal.save
      redirect_to [@requirement, @proposal], notice: 'Proposal was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /proposals/1
  def update
    if @proposal.update(proposal_params)
      redirect_to [@requirement, @proposal], notice: 'Proposal was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /proposals/1
  def destroy
    @proposal.destroy
    redirect_to [@requirement, :proposals], notice: 'Proposal was successfully destroyed.'
  end

  private
    def set_requirement
      @requirement = Requirement.find(params[:requirement_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def proposal_params
      params.require(:proposal).permit(:title, :description, :remark)
    end
end

app/controllers/requirements_controller.rb
class RequirementsController < ApplicationController
  before_action :set_requirement, only: [:show, :edit, :update, :destroy]

  # GET /requirements
  def index
    @requirements = Requirement.preload(:proposals).all

    if params[:format] == 'xlsx'
      workbook = RubyXL::Workbook.new
      sheet = workbook[0]
      sheet.sheet_name = "要求"

      %w[ID 状態 条件 要求 備考].each.with_index do |v, column|
        sheet.add_cell(0, column, v)
      end

      @requirements.each.with_index(1) do |r, row|
        [
          r.id,
          r.status,
          helpers.decorate(r.condition, text: true),
          helpers.decorate(r.description, text: true),
          helpers.decorate(r.remark, text: true),
        ].each.with_index do |v, column|
          cell = sheet.add_cell(row, column, v)
          cell.change_text_wrap(true) if v.to_s.include? "\n"
        end
        sheet.change_row_vertical_alignment(row, 'top')
      end

      sheet = workbook.add_worksheet("要件")
      %w[要求ID タイトル 要件 備考].each.with_index do |v, column|
        sheet.add_cell(0, column, v)
      end

      Proposal.all.each.with_index(1) do |r, row|
        [
          r.requirement_id,
          r.title,
          helpers.decorate(r.description, text: true),
          helpers.decorate(r.remark, text: true),
        ].each.with_index do |v, column|
          cell = sheet.add_cell(row, column, v)
          cell.change_text_wrap(true) if v.to_s.include? "\n"
        end
        sheet.change_row_vertical_alignment(row, 'top')
      end

      send_data workbook.stream.read, filename: '要件定義.xlsx'
    end
  end

  # GET /requirements/1
  def show
  end

  # GET /requirements/new
  def new
    @requirement = Requirement.new
  end

  # GET /requirements/1/edit
  def edit
  end

  # POST /requirements
  def create
    @requirement = Requirement.new(requirement_params)

    if @requirement.save
      redirect_to @requirement, notice: 'Requirement was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /requirements/1
  def update
    if @requirement.update(requirement_params)
      redirect_to @requirement, notice: 'Requirement was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /requirements/1
  def destroy
    @requirement.destroy
    redirect_to requirements_url, notice: 'Requirement was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_requirement
      @requirement = Requirement.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def requirement_params
      params.require(:requirement).permit(:status, :condition, :description, :remark)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def decorate(str, options = {})
    is_text = options[:text]

    unless is_text
      DomainModel.all.pluck(:name, :id).sort_by{|name| -name.size }.each do |name, id|
        b = content_tag(:b, link_to(name, domain_model_path(id)))
        str = str.gsub(name, b)
      end
    end

    domain_models = DomainModel.all.index_by(&:id)

    str = str.gsub(/\$domain:(\d+)\$/) do |match|
      if dm = domain_models[$1.to_i]
        if is_text
          dm.name
        else
          link_to dm.name, dm
        end
      else
        "$error$"
      end
    end
    str = str.gsub("\n", "<br/>") unless is_text

    if is_text
      str
    else
      str.html_safe
    end
  end
end

app/helpers/domain_models_helper.rb
module DomainModelsHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/requirements_helper.rb
module RequirementsHelper
end

app/views/domain_models/_form.html.haml
= form_with(model: domain_model, local: true) do |form|
  - if domain_model.errors.any?
    #error_explanation
      %h2
        = pluralize(domain_model.errors.count, "error")
        prohibited this domain_model from being saved:
      %ul
        - domain_model.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :name
    = form.text_field :name, id: :domain_model_name, size: '80'
  .field
    = form.label :desc
    = form.text_area :desc, id: :domain_model_desc, size: '80x10'
  .actions
    = form.submit

app/views/domain_models/edit.html.haml
%h1 Editing Domain Model
= render 'form', domain_model: @domain_model
= link_to 'Show', @domain_model
|
= link_to 'Back', domain_models_path

app/views/domain_models/index.html.haml
%p#notice= notice
%h1 Domain Models
%table
  %thead
    %tr
      %th Name
      %th Desc
      %th{:colspan => "3"}
  %tbody
    - @domain_models.each do |domain_model|
      %tr
        %td= domain_model.name
        %td= domain_model.desc
        %td= link_to 'Show', domain_model
        %td= link_to 'Edit', edit_domain_model_path(domain_model)
        %td= link_to 'Destroy', domain_model, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Domain Model', new_domain_model_path

app/views/domain_models/new.html.haml
%h1 New Domain Model
= render 'form', domain_model: @domain_model
= link_to 'Back', domain_models_path

app/views/domain_models/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @domain_model.name
%p
  %strong Desc:
  = @domain_model.desc

%article
  %h4
    出現箇所
  %table.table
    - @domain_model.requirements_ref.each do |r|
      %tr
        %td!= decorate(r.condition).gsub(@domain_model.name, content_tag(:span, @domain_model.name, style: 'color: red;'))
        %td!= decorate(r.description).gsub(@domain_model.name, content_tag(:span, @domain_model.name, style: 'color: red;'))
        %td!= decorate(r.remark).gsub(@domain_model.name, content_tag(:span, @domain_model.name, style: 'color: red;'))
        %td= link_to "Show", r

  %h4
    参照ではない出現箇所
  %table.table
    - @domain_model.requirements.each do |r|
      %tr
        %td!= decorate(r.condition).gsub(@domain_model.name, content_tag(:b, @domain_model.name))
        %td!= decorate(r.description).gsub(@domain_model.name, content_tag(:b, @domain_model.name))
        %td!= decorate(r.remark).gsub(@domain_model.name, content_tag(:b, @domain_model.name))
        %td= link_to "Show", r
  = link_to '全て参照に置き換える', [:replace, @domain_model], method: :post

= link_to 'Edit', edit_domain_model_path(@domain_model)
|
= link_to 'Back', domain_models_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rdd
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    %nav
      %ul
        %li= link_to 'Requirements', requirements_path
        %li= link_to 'Domain Models', domain_models_path

    = yield

app/views/proposals/_form.html.haml
= form_for [@requirement, @proposal] do |f|
  - if @proposal.errors.any?
    #error_explanation
      %h2= "#{pluralize(@proposal.errors.count, "error")} prohibited this proposal from being saved:"
      %ul
        - @proposal.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title, size: '80'
  .field
    = f.label :description
    = f.text_area :description, size: '80x10'
  .field
    = f.label :remark
    = f.text_area :remark, size: '80x10'
  .actions
    = f.submit 'Save'

app/views/proposals/edit.html.haml
%h1= link_to 'Requirement', @requirement

= render @requirement

%h1 Editing proposal

= render 'form'

= link_to 'Show', [@requirement, @proposal]
\|
= link_to 'Back', [@requirement, :proposals]

app/views/proposals/index.html.haml
%h1= link_to 'Requirement', @requirement

= render @requirement

%h1 Listing proposals

%table.table
  %thead
    %tr
      %th Title
      %th Description
      %th Remark
      %th
      %th
      %th

  %tbody
    - @proposals.each do |proposal|
      %tr
        %td= proposal.title
        %td= decorate proposal.description
        %td= decorate proposal.remark
        %td
          = link_to [@requirement, proposal], class: %i[btn btn-default] do
            %i.glyphicon.glyphicon-zoom-in
        %td
          = link_to [:edit, @requirement, proposal], class: %i[btn btn-default] do
            %i.glyphicon.glyphicon-edit
        %td
          = link_to [@requirement, proposal], method: :delete, data: { confirm: 'Are you sure?' }, class: %i[btn btn-danger] do
            %i.glyphicon.glyphicon-remove

%br

= link_to 'New Proposal', [:new, @requirement, :proposal]

app/views/proposals/new.html.haml
%h1= link_to 'Requirement', @requirement

= render @requirement

%h1 New proposal

= render 'form'

= link_to 'Back', [@requirement, :proposals]

app/views/proposals/show.html.haml
%h1= link_to 'Requirement:', @requirement
= render @requirement

%h1 Proposal
%p#notice= notice

%p
  %b Title:
  = @proposal.title
%p
  %b Description:
  = @proposal.description
%p
  %b Remark:
  = @proposal.remark

= link_to 'Edit', [:edit, @requirement, @proposal]
\|
= link_to 'Back', [@requirement, :proposals]

app/views/requirements/_form.html.haml
= form_with(model: requirement, local: true) do |form|
  - if requirement.errors.any?
    #error_explanation
      %h2
        = pluralize(requirement.errors.count, "error")
        prohibited this requirement from being saved:
      %ul
        - requirement.errors.full_messages.each do |message|
          %li= message

  .field
    = form.label :status
    = form.select :status, Requirement.status.options
  .field
    = form.label :condition
    = form.text_area :condition, id: :requirement_condition, size: '80x10'
  .field
    = form.label :description
    = form.text_area :description, id: :requirement_description, size: '80x10'
  .field
    = form.label :remark
    = form.text_area :remark, id: :requirement_remark, size: '80x10'
  .actions
    = form.submit

app/views/requirements/_requirement.html.haml
%p
  %strong Status:
  = @requirement.status.text
%p
  %strong Condition:
  = decorate @requirement.condition
%p
  %strong Description:
  = decorate @requirement.description
%p
  %strong Remark:
  = decorate @requirement.remark

app/views/requirements/edit.html.haml
%h1 Editing Requirement
= render 'form', requirement: @requirement
= link_to 'Show', @requirement
|
= link_to 'Back', requirements_path

app/views/requirements/index.html.haml
%p#notice= notice
%h1
  Requirements
  = link_to requirements_path(format: :xlsx), class: %i[btn btn-primary] do
    %i.glyphicon.glyphicon-download
%table.table
  %thead
    %tr
      %th ID
      %th Status
      %th Condition
      %th Description
      %th Remark
      %th{:colspan => "4"}
  %tbody
    - @requirements.each do |requirement|
      %tr
        %td= requirement.id
        %td
          - if requirement.status == :fixed
            %span.btn.btn-default= decorate requirement.status.text
          - else
            %span.btn.btn-danger= decorate requirement.status.text
        %td= decorate requirement.condition
        %td= decorate requirement.description
        %td= decorate requirement.remark
        %td
          = link_to requirement, class: %i[btn btn-default] do
            %i.glyphicon.glyphicon-zoom-in
        %td
          = link_to edit_requirement_path(requirement), class: %i[btn btn-default] do
            %i.glyphicon.glyphicon-edit
        %td
          = link_to requirement, method: :delete, data: { confirm: 'Are you sure?' }, class: %i[btn btn-danger] do
            %i.glyphicon.glyphicon-remove
        %td
          = link_to [requirement, :proposals] do
            - if requirement.proposals.size == 0
              %button.btn.btn-primary
                Proposals
                .badge= requirement.proposals.size
            - else
              %button.btn.btn-secondary
                Proposals
                .badge= requirement.proposals.size
%br/
= link_to 'New Requirement', new_requirement_path

app/views/requirements/new.html.haml
%h1 New Requirement
= render 'form', requirement: @requirement
= link_to 'Back', requirements_path

app/views/requirements/show.html.haml
%p#notice= notice

%h1 Requirement
= render @requirement

= link_to 'Edit', edit_requirement_path(@requirement)
|
= link_to 'Back', requirements_path

%h1 Proposals
= link_to "Proposals(#{@requirement.proposals.size})", [@requirement, :proposals]